### PR TITLE
Initial work on getting tapestry command working

### PR DESCRIPTION
**Pull request by jonsherrard**
Bits to figure out:

 - Have client bundle consume the tree
 - Flash of unstyled stuff
 - Code duplication in boot.js // Really odd bug on transpilation where the configPath variables are misnamed
 - `tapestry init` to bootstrap a project
 - Various other bugs and tidying

### CODE REVIEW

**Comment by thomasdigby** [comment]
[Rewrite server to ES2015](https://trello.com/c/AY2xmAiL/24-rewrite-server-to-es2015)

**Comment by jonsherrard** [comment]
@thomasdigby is there a new Trello board?

**Comment by thomasdigby** [comment]
Ah yes, yes there is. Part of 'Lennon' now.

**Comment by jonsherrard** [comment]
Ah. Do add me when you get a chance!

**Pull request merged**
