### PR TITLE
Refactored boot.js to be DRY

### PR DESCRIPTION
**Pull request by ecoad**
Removed code present in both sides of the main conditional.

### CODE REVIEW

**Comment by ecoad** [comment]
Hold merging this until further testing.

**Comment by thomasdigby** [comment]
@mathewhawley This will definitely be overwritten with your CLI work, right?

**Comment by mathewhawley** [comment]
@thomasdigby , na I haven't been touching `boot.js` – just the `bin/tapestry`

**Comment by jonsherrard** [comment]
This doesn't work code doesn't work in it's current state - maybe something to do with `const`, maybe something to do with how Webpack treats dynamic requires...

**Pull request closed without merging**
