### PR TITLE
Bootstrap project

### PR DESCRIPTION
**Pull request by thomasdigby**
#### What have you done
Added a `tapestry init` command to create some sensible project defaults, in this case, a `components` directory with a base, page and post component, an empty `public` directory, a `tapestry.config.js` file and a `package.json`.

If any of the files/directories exist they will be skipped, apart from `package.json` which will do a deep object merge with priority to the project's file.

#### Why have you done it
#29 

Notice the `rfc` label on the right, let's get commenting!

### CODE REVIEW

**Comment by jonsherrard** [comment]
Awesome work!

1: I feel like the `package.json` is overreaching, they'll need to have `npm install`'d `tapestry-wp` in order to have access to the `init` command, and `npm init` does a pretty great job walking you through setting up your `package.json`.

2: _We need to talk about Base_. I've wondered to myself if it's quite a confusing concept, and we could deprecate it in favour of documentation describing how to have shared headers/footers/etc across `Post` and `Page`, rather than a specific component/API. I.E:

```js
import Header from '../partials/header/'
import Footer from '../partials/footer/'
const = Base = (props) =>
   <html>
      <Header />
        {props.children}
      <Footer />
   </html>
```


```js
import Base from '../partials/base/'
const Post = (props) =>
  <Base>
     <h1>{props.title.rendered}</h1>
     {props.the_content.rendered}
   </Base>
```

**Comment by thomasdigby** [comment]
`package.json` is outta here! On your `<Base />` point, is it not required for react-router as an entry point? Much like a generic `<App />` component?

**Comment by jonsherrard** [comment]
I think it could look like this
```
const DefaultRoutes = ({ Category, Post, Page, Home }) =>
<Route
      path='/'
      component={HomeLoader}
      tag={Home} />
    <Route
      path='about/:slug'
      component={PageLoader}
      tag={Page} />
    <Route
      path=':category(/:subcategory)'
      component={CategoriesLoader}
      tag={Category} />
    <Route
      path=':category(/:subcategory)/:slug/:id'
      component={PostLoader}
      tag={Post} />
  </Route>
```

But that also requires some explaining in the documentation - but perhaps is a closer metaphor to a "default front page" you get in WordPress. If we had:

* Components
  - FrontPage 
  - Post
  - Page
  - Archive
  - Term
  - Author

A WordPress user would understand all of those names. I haven't arrived at a conclusion on either of them yet.... FrontPage feels slightly wrong, having a Base component feels a bit better if we explain it actually...

**Comment by thomasdigby** [comment]
Cool cool, I'll give that routing set-up a try.

That list looks uber-wordpressy, which I think we're agreed _should_ be the intention wherever possible. I'll add `Home` -> `FrontPage` in another ticket. Do you see term, archive and author as requirements for the bootstrapping?

**Pull request merged**
