### PR TITLE
Maintainence/project updates

### PR DESCRIPTION
**Pull request by jonsherrard**
#### What have you done
Updated project dependencies

#### Why have you done it
Housekeeping and React 16 compat

#### Testing carried out to prevent breaking changes
Installed on a couple of large projects, and test suite passing.

### CODE REVIEW

**Comment by thomasdigby** [comment]
Woah, it works?

**Comment by jonsherrard** [comment]
Yeeep, did sourceMaps ever work before? Because in my testing I could click through to Post.js and stuff. Wasn't sure if that was React 16 or just something I've missed. Anyhoo. All looking good.

**Comment by jonsherrard** [comment]
Just need to fix all these stupid version that ~i've~ yarn's done.

**Comment by thomasdigby** [comment]
Duped by #299

**Pull request closed without merging**
