### PR TITLE
Add polyfills

### PR DESCRIPTION
**Pull request by thomasdigby**
#### What have you done
Added `babel-polyfill` to the client bundle

#### Why have you done it
`Promise` and other native methods weren't polyfilled for older browsers

#### Testing carried out to prevent breaking changes
No tests breaking, tested across older browsers

### CODE REVIEW

**Comment by thomasdigby** [comment]
This is maybe a pre-cursor to utilising something like [`preset-env`](https://babeljs.io/docs/plugins/preset-env/) with a [`browserslist`](https://github.com/ai/browserslist) config.

**Comment by jonsherrard** [comment]
OK I: How does this affect bundle size?

**Comment by jonsherrard** [comment]
Ok I = "out of interest" not sure what happened with autocorrect there

**Comment by thomasdigby** [comment]
Yes, oh my, I was looking at the incorrect chunk, it's almost 300% larger.

**Comment by thomasdigby** [comment]
Hoowee, yep `core-js` is over 80k, I'll have a look into `preset-env` and see if it can provide a configurable polyfill rather than _the kitchen sink_.

**Comment by mathewhawley** [comment]
If it helps, this is the article by Philip Walton that I referenced a while ago that outlines his strategies for polyfills (it also has a snippet of code that shows to import only what you need from `core-js`). The babel `env` preset or his way seem like two good routes? https://philipwalton.com/articles/loading-polyfills-only-when-needed/

**Comment by thomasdigby** [comment]
Nice. What are our thoughts on possible global namespace conflicts? I had a `babel-polyfill` conflict with a previous project, would we want to keep these polyfills internal (as a lib might do) or are we happy to say, Tapestry is an opinionated framework, it comes with this stuff.

**Comment by mathewhawley** [comment]
I think minimal polyfills needed for tapestry would be ideal (to keep the base footprint as small as possible), with the ability for users to add polyfills as they desire would be pretty necessary? This can have big impact on performance, and a user's ability to support browsers they're targeting. Probably not something you'd want to restrict? If this was purely a node module, then you'd probably be fine just bundling all the polyfills in to cover all bases – as it's a browser based 'lib', custom polyfilling is probably a good idea? Maybe we'd need to document which polyfills are included?

**Comment by mathewhawley** [comment]
But yea not sure about conflicts – havn't come across that myself yet

**Comment by jonsherrard** [comment]
In the spirit of WordPress's incredible backwards compat, it'd be sweet if everything worked out of the box, part of me feels like it could work back to IE8, but `React-DOM` only supports IE9.

I think in terms of some the babel-stages, we've already opined on some functionality. Polyfilling small stuff like, Promise, Object Assign doesn't feel like too great a sin.

Certainly a documentation section on browser libraries you get "out of the box" would help clear things up for users.

**Comment by thomasdigby** [comment]
I think we'll include a `Promise` polyfill and call it quits, I think anything else we need has a `babel` helper replacement.

**Comment by thomasdigby** [comment]
Updated to include `es6-promise`

**Pull request merged**
