### PR TITLE
Reconfigure logging

### PR DESCRIPTION
**Pull request by thomasdigby**
Updated the internal logging to use a single instance of `winston`, removed most of our logging methods,`error` `errorObject` etc. and replaced with `notify` which will print a string to the console.

Added `chalk` colours to the `debug` logs to highlight important data.

I'm going to add more `info` and `debug` logs throughout the codebase, hence the `!MERGE`

### CODE REVIEW

**Comment by jonsherrard** [comment]
I like it 👍 !

Should we align the verb or noun:

`log, notify`

or, 

`logger, notifier`

**Comment by thomasdigby** [comment]
Mmmm yes, I'll update it to `log`. `log.error('bad thing')`, `log.debug('yolo)`

**Comment by jonsherrard** [comment]
@thomasdigby is this ready to go in?

**Comment by thomasdigby** [comment]
Could maybe do with some more logs but that can come in a separate ticket

**Comment by thomasdigby** [comment]
@jonsherrard Whaddya thoughts on this? Shall we mergey?

**Pull request merged**
